#!/bin/bash
MERCURY_TESTS_DIR=$(sst-config SST_ELEMENT_TESTS mercury)
cd "$MERCURY_TESTS_DIR" || exit
CXX=$(sst-config --CXX)
ELEMENT_CXXFLAGS=$(sst-config --ELEMENT_CXXFLAGS)
ELEMENT_LDFLAGS=$(sst-config --ELEMENT_LDFLAGS)
INCLUDE_DIR=$(sst-config SST_ELEMENT_SOURCE mercury)
SST_ELEMENT_LIBRARY_BUILDDIR=$(sst-config SST_ELEMENT_LIBRARY SST_ELEMENT_LIBRARY_BUILDDIR)
SST_ELEMENT_LIBRARY_BUILDDIR+="/src"
SST_ELEMENT_LIBRARY_LIBDIR=$(sst-config SST_ELEMENT_LIBRARY SST_ELEMENT_LIBRARY_LIBDIR)
LIB="hg"

COMPILE="$CXX $ELEMENT_CXXFLAGS -I$INCLUDE_DIR -I$SST_ELEMENT_LIBRARY_BUILDDIR -g -O0 -c testme.cc"
echo "$COMPILE"
$COMPILE
LINK="$CXX $ELEMENT_LDFLAGS -L$SST_ELEMENT_LIBRARY_LIBDIR -l$LIB -o testme testme.o"
echo "$LINK"
$LINK
